### ISSUE TITLE
Horizontal scrolling not working inside every card item

### ISSUE THREAD

**Issue by shruti-techindustan** [yarolegovich/DiscreteScrollView#175] opened 2019-07-11 10:15 UTC
Hi
Each Recyclerview item I am using horizontal scroll viiew but that view is not scrolling horizontally. When i scroll it move to next item of card.
Thanks

**Comment by yarolegovich** [comment] 2020-08-01 14:54
A duplicate of #155

**Closed by yarolegovich** 2020-08-01 14:54 UTC
