### ISSUE TITLE
how  to set the width and height dynamically

### ISSUE THREAD

**Issue by hyr0318** [yarolegovich/DiscreteScrollView#139] opened 2018-09-13 02:52 UTC
in xml  The width and height are not fixed
For example：
    <android.support.v7.widget.CardView
      android:id="@+id/root"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      app:cardElevation="0dp"
      android:layout_gravity="center"
>
    <ImageView
        android:scaleType="centerCrop"
        android:id="@+id/iv_pic"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

    </android.support.v7.widget.CardView>

Set the width and height in the code
For example：
        int width = DisplayUtil.getScreenWidth(holder.itemView.getContext()) - DisplayUtil.dp2px(
            holder.itemView.getContext(), 105);
        
        Utils.setRatioWidthHeight(registerTypeOneBinding.root, width,
            inviteRegisterTypeOne.getHeight(),
            inviteRegisterTypeOne.getWidth());

That's the breakdown
RecyclerViewProxy.getMeasuredChildForAdapterPosition(RecyclerViewProxy.java:52)
DiscreteScrollLayoutManager.layoutView(DiscreteScrollLayoutManager.java:225)
DiscreteScrollLayoutManager.layoutViews(DiscreteScrollLayoutManager.java:214)
DiscreteScrollLayoutManager.fill(DiscreteScrollLayoutManager.java:192)
DiscreteScrollLayoutManager.onLayoutChildren(DiscreteScrollLayoutManager.java:120)

so how  to set the width and height dynamically not fixed ？ 

think you

**Comment by yarolegovich** [comment] 2020-08-01 13:02
A duplicate of #20

**Closed by yarolegovich** 2020-08-01 13:02 UTC
