### ISSUE TITLE
Not Resizing with Soft Keyboard

### ISSUE THREAD

**Issue by bhylak** [yarolegovich/DiscreteScrollView#85] opened 2018-02-10 23:56 UTC
The DiscreteScrollView is not resizing with soft keyboard.

Confirmed as a bug because I swapped the DSV with a RecyclerView (leaving all the same attributes) and it adjusts as expected. 

Here's one of the items being displayed: 

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        android:orientation="vertical"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:android="http://schemas.android.com/apk/res/android">
    <View
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
    />
    <ScrollView android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:fillViewport="true">

    <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:id="@+id/item_picturequestion">

        <ImageButton android:layout_width="wrap_content" android:layout_height="wrap_content"
                     android:background="@drawable/surveyquestions_arrow"
                     android:rotation="-180"
                     android:layout_marginStart="24dp"
                     android:layout_marginEnd="24dp"
                     android:layout_gravity="center"/>

        <LinearLayout android:layout_width="0dp"
                      android:layout_height="wrap_content"
                      android:layout_weight="2"
                      android:orientation="vertical">

            <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/tv_questionall_title"
                    android:textAppearance="@style/Heading.Large"
                    android:gravity="center_vertical"
                    tools:text="What country are you from?"
                    android:textSize="48sp"/>
            <RelativeLayout
                    android:layout_width="wrap_content"
                    android:layout_marginTop="24dp"
                    android:layout_height="wrap_content">

                <ImageView android:layout_width="wrap_content"
                           android:layout_centerVertical="true"
                           android:layout_toEndOf="@id/spinner_questiondropdown"
                           android:layout_marginStart="-28dp"
                           android:background="@drawable/ic_all_downchevron"
                           android:layout_height="wrap_content"/>

                <Spinner
                        android:layout_width="wrap_content"
                        android:layout_alignParentStart="true"
                        android:minWidth="140dp"
                        android:layout_height="40dp"
                        android:paddingEnd="20dp"
                        android:paddingStart="0dp"
                        android:background="@drawable/spinner_background"
                        android:id="@+id/spinner_questiondropdown"/>
            </RelativeLayout>

        </LinearLayout>

        <ImageButton android:layout_width="wrap_content" android:layout_height="wrap_content"
                     android:background="@drawable/surveyquestions_arrow"
                     android:layout_marginEnd="24dp"
                     android:id="@+id/btn_questionall_next"
                     android:layout_marginStart="24dp"
                     android:layout_gravity="center|end"/>

    </LinearLayout>
    </ScrollView>
    <View
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
    />
</LinearLayout>

and the declaration of the scrollview

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:fitsSystemWindows="true"
              xmlns:android="http://schemas.android.com/apk/res/android">
<android.support.v7.widget.RecyclerView
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/indicator_card_yellow"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_gravity="center_vertical"
        android:orientation="horizontal"
        android:id="@+id/rv_survey_questions"
        tools:listitem="@layout/item_questiondropdown"/>
</LinearLayout>

**Comment by yarolegovich** [comment] 2018-02-11 07:29
Thanks for discovering the causes. I'll look into it.

**Comment by yarolegovich** [comment] 2018-02-12 11:31
I've just done some experimenting and in a sample project DiscreteScrollView works perfectly fine with different soft input modes. 
If you provide screenshots of a DiscreteScrollView and a RecyclerView, I will try to give an advice, but I guess your problem is in your layout where DiscreteScrollView is defined and it has nothing to do with the library.

**Comment by yarolegovich** [comment] 2018-02-12 15:49
I've probably figured this out. Can you please check whether version `1.4.5` works for you?

**Comment by yarolegovich** [comment] 2018-02-12 16:09
I've probably figured this out. Can you please check whether version `1.4.5` works for you?

**Comment by yarolegovich** [comment] 2018-02-12 16:20
I've probably figured this out. Can you please check whether version `1.4.6` works for you?

**Comment by yarolegovich** [comment] 2018-04-01 09:10
Fixed in `1.4.6`.

**Closed by yarolegovich** 2018-04-01 09:10 UTC
