### ISSUE TITLE
Can not give dynamic height to items 

### ISSUE THREAD

**Issue by karanatwal** [yarolegovich/DiscreteScrollView#40] opened 2017-08-22 13:56 UTC
Hello, I am in a great problem ..I am using your library for showing images. There are different types of images some are portrait some are landscape but I have tried every possibility but I am unable to give dynamic height. i tried in `onCreateViewHolder` and in `onBindViewHolder` .Please help

**Comment by yarolegovich** [comment] 2017-09-03 05:49
Probably a duplicate of #20

**Closed by yarolegovich** 2017-09-03 05:49 UTC
