### ISSUE TITLE
ScrollView isn't working properly with height of item = wrap_content 

### ISSUE THREAD

**Issue by amrfarid140** [yarolegovich/DiscreteScrollView#25] opened 2017-06-21 12:38 UTC
I am trying to use this library with a CardView as a viewholder. The card view height is set to wrap_content. The card_view has a textview inside it which makes it bigger or smaller according to the size of this text_view.

The ScrollView always show items with height equal to the height of the first item. Is there a way to make such behaviour work with DiscreteScrollView ?

**Comment by Junaid-Ahmed-Qureshi** [comment] 2017-07-07 13:56
I'm facing the similar issue. Please fix it in the library.

**Comment by yarolegovich** [comment] 2017-09-03 05:52
Probably a duplicate of #20

**Closed by yarolegovich** 2017-09-03 05:52 UTC
