### ISSUE TITLE
DiscreteScrollView inside DiscreteScrollView

### ISSUE THREAD

**Issue by mohan9nimo** [yarolegovich/DiscreteScrollView#171] opened 2019-06-12 05:15 UTC
anyone tried DiscreteScrollView inside DiscreteScrollView. Its not working.

**Comment by yarolegovich** [comment] 2020-08-01 14:22
A duplicate of #155 (DiscreteScrollView is RecyclerView)

**Closed by yarolegovich** 2020-08-01 14:22 UTC

**Comment by Calvinnncy97** [comment] 2020-11-19 14:03
Does anyone manage to find a solution to this? I can't seem to find a way
