### ISSUE TITLE
Not Support Multiple Layout with different width and Height

### ISSUE THREAD

**Issue by mahimrocky** [yarolegovich/DiscreteScrollView#161] opened 2019-01-25 12:43 UTC
If i use multiple layout with different size this library always take the first item size. And converted to same size for all item

**Comment by yarolegovich** [comment] 2020-07-30 04:51
A duplicate of https://github.com/yarolegovich/DiscreteScrollView/issues/20

**Closed by yarolegovich** 2020-07-30 04:51 UTC
