### ISSUE TITLE
The first image centerd 

### ISSUE THREAD

**Issue by mataleao** [yarolegovich/DiscreteScrollView#183] opened 2019-11-09 05:49 UTC
Hi,

would like to know why the first image starts centered?

![image](https://user-images.githubusercontent.com/623443/68523670-e8130080-029a-11ea-8887-ef7b900f9d0f.png)

How do I align it left ?

Thanks in advance

**Comment by infinity8942** [comment] 2019-11-27 01:21
Duplicate of #100

**Closed** 2020-07-30 04:12 UTC
