### ISSUE TITLE
Is it possible to overlap one item over other?

### ISSUE THREAD

**Issue by muhaym** [yarolegovich/DiscreteScrollView#137] opened 2018-09-04 18:49 UTC
I am looking something like Cylindrical Effect, where we can see previous and next item, but partially under the current item.

**Comment by passself** [comment] 2019-01-25 10:14
the same problem

**Comment by pwillmann** [comment] 2019-02-05 23:15
see https://github.com/yarolegovich/DiscreteScrollView/issues/140#issuecomment-460842155

**Comment by yarolegovich** [comment] 2020-07-30 04:45
A duplicate of https://github.com/yarolegovich/DiscreteScrollView/issues/140

**Closed by yarolegovich** 2020-07-30 04:45 UTC
