### ISSUE TITLE
scrollToPosition is ignored with InfiniteScrollAdapter

### ISSUE THREAD

**Issue by PedroBernils** [yarolegovich/DiscreteScrollView#69] opened 2017-12-07 21:07 UTC
This seems to be related to [this issue](https://github.com/yarolegovich/DiscreteScrollView/issues/68), but basically, if you set your adapter as an InfiniteScrollAdapter, scrollToPosition simply does nothing.

Using a normal adapter works as intended.

**Comment by yarolegovich** [comment] 2018-02-03 14:25
Let's assume that's a duplicate of #68.

**Closed by yarolegovich** 2018-02-03 14:25 UTC
