### ISSUE TITLE
Is pagination supported?

### ISSUE THREAD

**Issue by preyesm** [yarolegovich/DiscreteScrollView#164] opened 2019-02-18 12:52 UTC
Hi, the library is really good, thanks for that. I wanted to know if we can implement endless scroll in the DiscreteScrollView library to support pagination

**Comment by HakorimanaEmmanuel** [comment] 2019-03-09 10:06
me too i want to know

**Comment by yarolegovich** [comment] 2020-07-30 04:24
A duplicate of:
https://github.com/yarolegovich/DiscreteScrollView/issues/169
The library provides callbacks necessary to implement pagination.
I think the feature is too case-specific.

**Closed by yarolegovich** 2020-07-30 04:24 UTC
