### ISSUE TITLE
Item size has to be fixed in discrete scrollview

### ISSUE THREAD

**Issue by archit2495** [yarolegovich/DiscreteScrollView#58] opened 2017-10-25 06:44 UTC
The items that are to be displayed inside the discrete scrollview the size has to be predefined and cannot be set as match_parent.

**Comment by yarolegovich** [comment] 2018-02-03 13:02
It can be set as `match_parent` or `wrap_content`, however it's dependent on the size of the first item. I assume the issue is a duplicate of #20

**Closed by yarolegovich** 2018-02-03 13:02 UTC

**Comment by bhylak** [comment] 2018-02-07 01:37
Setting match_parent for all of the items didn't work.
