### ISSUE TITLE
supportLibVersion = 28.0.0

### ISSUE THREAD

**Issue by hongtou820** [yarolegovich/DiscreteScrollView#145] opened 2018-10-10 02:49 UTC
error: cannot find symbol method values()
DuscreteScrollView
 layoutManager = new DiscreteScrollLayoutManager(
                getContext(), new ScrollStateListener(),
                Orientation.values()[orientation]);
        setLayoutManager(layoutManager);

**Comment by yarolegovich** [comment] 2020-08-01 12:53
Supposedly a duplicate of #134

**Closed by yarolegovich** 2020-08-01 12:53 UTC
